apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nst9sb9gc-python
  janus-idp.io/tekton: nst9sb9gc-python
  backstage.io/kubernetes-id: nst9sb9gc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nst9sb9gc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
