apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nst9sb9gc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nst9sb9gc-python 
  name: nst9sb9gc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nst9sb9gc-python 
